server:
  ssl:
    key-store-type: PKCS12
    key-store: ${KEYSTORE}
    key-store-password: ${KEYSTORE_PASSWORD}
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
  port: 8443

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIEND_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

logging:
  level:
    root: debug
    org.springframework:
        security: debug
        web: debug
