server:
  ssl:
    key-store-type: PKCS12
    key-store: ${KEYSTORE}
    key-store-password: ${KEYSTORE_PASSWORD}
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  port: 8443

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIEND_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope:
                - email
                - profile
              redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
          provider:
            google:
              issuer-uri: https://accounts.google.com

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  expiration: 3600
  signing-algorithm: RS256

logging:
  level:
    root: debug
    org.springframework:
        security: debug
        web: debug
